[package]
org = "wso2healthcare"
name = "tokenResponseMediationPolicy"
version = "1.0.7"
distribution = "2201.5.5"
keywords = ["choreo-apim-mediation-policy","choreo-apim-mediation-request-flow","choreo-apim-mediation-response-flow","choreo-apim-mediation-fault-flow"]
# visibility = "private"

[build-options]
observabilityIncluded = true
